### ISSUE TITLE
[Bug][1.3PR] Rope-Bridge may randomly break /help command

### ISSUE THREAD

**Issue by Aedda** [MrTrollNugNug/Rope-Bridge#1]
As reported by HelpFixer, Rope-Bridge incorrectly overrides compareTo() on 2 help commands. Most likely returning a default of 0 rather than the actual compare result.

```[05:00:08] [Server thread/WARN]  [com.matthewprenger.helpfixer.HelpFixer]: Command [ropebridge, com.mrtrollnugnug.ropebridge.RopeBridgeCommand] incorrectly overrides compareTo: %s```
```[05:00:08] [Server thread/WARN]  [com.matthewprenger.helpfixer.HelpFixer]: Command [ropebridge, com.mrtrollnugnug.ropebridge.RopeBridgeCommand] incorrectly overrides compareTo: %s```

**Comment by Morpheus1101** [comment]
Has this issue been fixed?

**Comment by Aedda** [comment]
This issue is not fixed as of the 1.4.0 update 4 hours ago. However according to the commit history Darkhax has fixed the issue in source.

**Comment by LewisMcReu** [comment]
The command was removed, and when readded will be fixed.
As for now, this issue is irrelevant.
