### ISSUE TITLE
Config Option

### ISSUE THREAD

**Issue by Medusalem** [MrTrollNugNug/Rope-Bridge#17]
It would be awesome if the Amount of energy you need to spend to destroy on of this things would be an option in the config!

The bridges are super easy to destroy and super hard to fix in the same optic than it was before!

But the look awesome :)

**Comment by Cazsius** [comment]
I see, I will make the bridge breaking time longer, and maybe add a bridge replacing tool, so you can place the bridge blocks alone without having the actual blocks to fix bridges, though I don't see the need for the config option as this is a bug.

**Comment by Medusalem** [comment]
:)

**Comment by KiriCattus** [comment]
Fixed pending release.
