### ISSUE TITLE
Rope Ladder replacing fluids [1.11.2]

### ISSUE THREAD

**Issue by UpcraftLP** [MrTrollNugNug/Rope-Bridge#18]
When shooting a rope ladder the ladder does not stop when hitting a fluid block, and instead replaces the fluid but gets broken afterwards by the liquid.

My suggestion is to stop when hitting any liquid instead of repalcing these.

Minecraft Version: 1.11.2
Forge Version: 13.20.0.2315
Mod Version: 1.11.2-2.0.5

**Comment by UpcraftLP** [comment]
@Cazsius actually it's more a bug than a feature request, lol

**Comment by Tfarcenim** [comment]
not an issue anymore since the ladders support waterlogging
