### ISSUE TITLE
Rope bridge breaking not working [bug]

### ISSUE THREAD

**Issue by bcatly** [MrTrollNugNug/Rope-Bridge#19]
Hi! When I try to break the whole rope bridge my sneak breaking with the grappling hook, it does not actually break the bridge. What happens is that the block becomes invisible and after logging back in, the block will not have been broken but still be in that location.

**Comment by Cazsius** [comment]
Can you put a game version and mod version please?

**Comment by bcatly** [comment]
The version I am currently using is 1.10.2 and mod version 1.10.2-2.0.5

**Comment by Cazsius** [comment]
1.10.2 is not curently supported, and I can't seem to replicate this problem, closing the issue.
