### ISSUE TITLE
BB Gun is render in the wrong way (1.10.2)

### ISSUE THREAD

**Issue by Lightone** [MrTrollNugNug/Rope-Bridge#2]
like this

![2017-02-12_20 26 05](https://cloud.githubusercontent.com/assets/2113099/22868299/6fba608e-f162-11e6-8443-ea86fd1b9fbb.png)

Tested only with forge (1.10.2 - 12.18.3.2185)

**Comment by Cazsius** [comment]
This is a known issue, will be fixed in next version. Thanks!

**Comment by LewisMcReu** [comment]
This issue has now been fixed.

**Comment by Cazsius** [comment]
FIXED!
