### ISSUE TITLE
1.12.1 - Crash when launching controls in menu!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MrTrollNugNug/Rope-Bridge#20]
https://gist.github.com/P3rf3ctXZer0/ddc32cf9c3a0b1ea433040026b32be73

**Comment by Cazsius** [comment]
Do you mean the vanilla controls screen that lists all controls for minecraft?

**Comment by P3rf3ctXZer0** [comment]
Yes

**Comment by Cazsius** [comment]
I believe I've fixed it, hotfix will roll out tommorow.

**Comment by Cazsius** [comment]
https://minecraft.curseforge.com/projects/rope-bridge/files/2465994
