### ISSUE TITLE
Crafting Problem

### ISSUE THREAD

**Issue by Zaracan** [MrTrollNugNug/Rope-Bridge#22]
Strange one, I can craft the grappling hook but not the barrel or the stock despite following the clear recipes. Any ideas? Minecraft, forge and this mod all on latest versions (1.12) with no other mods running and using only vanilla ingredients. 

Cheers!

**Comment by Cazsius** [comment]
I've updated the description but replace the string with rope in the crafting table.
Rope recipe is the following:
S = String
V = Vine

SV
VS
SV
