### ISSUE TITLE
{ 1.12.2 } Editing the Config file doesn't do anything.

### ISSUE THREAD

**Issue by The1stRazer** [MrTrollNugNug/Rope-Bridge#23]
As of the overview for this mod, it says that u can change the requirement for making a rope bridge to none, I've went to the Config file, then changed all the Requirements to 0, also switched the sloop warning to true, but when i went back to the game, and tried the bridge maker again, it still tells me that it needs certain amount of slabs and ropes to make it, did i do anything wrong?
i have the latest version of forge, the mod, and Minecraft, also tried restarting the game several time.

wish to get an answer soon!
Appreciate the help in advance. ^-^

**Comment by Cazsius** [comment]
I'll have to investigate, though this seems to be an issue with slab requirements, not the slope warning.

**Comment by KiriCattus** [comment]
Fixed pending release.
