### ISSUE TITLE
Crafting not working

### ISSUE THREAD

**Issue by DeMash077** [MrTrollNugNug/Rope-Bridge#24]
Currently running 12.2 version of the mod along with 12.2 forge, it's letting me craft the grappling hook but none of the other pieces of the bridge building gun. There was another user with the same problem, but they got an unrelated answer and the question was closed.

**Comment by dpaci** [comment]
Same here, hope it gets fixed

**Comment by Cazsius** [comment]
I apologise, I did not understand the last person. I'm investigating this issue now.

**Comment by Cazsius** [comment]
I've just tested this on the latest version of rope bridge. 1.12-2.0.7 and forge version 14.23.4.2708 and had zero issues. Maybe you are using a modpack with the recipes disabled?

**Comment by dpaci** [comment]
I'm not using any modpack, just this mod. I'm only able to craft the Grappling Hook as the OP claims to be too. I fixed this by temporarily setting myself to Creative mode and just pull the weapon from that.

**Comment by Cazsius** [comment]
@djosepaci I tested crafting recipes and had zero issues, get JEI or something to check recipes maybe.
