### ISSUE TITLE
No-material-config fails for ladder gun/Durability

### ISSUE THREAD

**Issue by noobanidus** [MrTrollNugNug/Rope-Bridge#26]
Setting the required slabs to 0 and the required rope to 0 in the config functions perfectly fine for the rope bridge gun, but when attempting to fire a ladder I get "You need 0 slabs and 0 rope to make this".

I believe this stems from the fact that the message is predicated on both `findType` function not returning null, and hasMaterials returning true. I'll try to make a PR for this at some point -- this is mostly a reminder.

Additionally, the rope bridge gun uses durability (which I noticed -- the inventory clutter is the main reason I disabled the materials, and I intend to make the recipe itself more expensive in my pack to compensate) but the ladder gun does not.

Is this an intended disparity?

**Comment by Tfarcenim** [comment]
fixed in 2.1
