### ISSUE TITLE
[1.15.2] Bridge Gun crashes server.

### ISSUE THREAD

**Issue by Gbergz** [MrTrollNugNug/Rope-Bridge#32]
Title^

**Forge**: 31.1.0
**Mod-Version**: 1.2
**Minecraft-Version**: 1.15.2

**Crash-Report**: https://gist.github.com/Gbergz/3372c9d787d759fe037a9d3057e0ee11

One of my players playing my pack [TNP Limitless 2](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-2) reported this so I have no further information regarding it. Only the crash report.

- Gbergz

**Comment by Yoosk** [comment]
Another report from our server this time:
http://s.yoosk.pl/k9nuJ

Forge: 31.1.12
Mod-Version: 1.15.1-1.2
Minecraft-Version: 1.15.2

**Comment by Tfarcenim** [comment]
fixed in https://www.curseforge.com/minecraft/mc-mods/rope-bridge/files/3019566, but I don't have any permissions here so can't do anything.

**Comment by jriwanek** [comment]
@Tfarcenim Should have prodded me. xD
