### ISSUE TITLE
 Some bridge blocks connect incorrectly

### ISSUE THREAD

**Issue by WenXin20** [MrTrollNugNug/Rope-Bridge#36]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Rope Bridge v1.3`

Some bridge blocks are using an incorrect model.
![2020-08-03_20 59 42](https://user-images.githubusercontent.com/12000593/89245503-8f288c80-d5ce-11ea-90b0-347f2b44d599.png)

**Comment by KiriCattus** [comment]
Closing this issue as a duplicate of #41 but will make notes that the issue persists across versions :)
