### ISSUE TITLE
[1.7.10] Rope Bridge view distance is too short.

### ISSUE THREAD

**Issue by LeoMantys** [MrTrollNugNug/Rope-Bridge#4]
I love your mod! Fantastic work!
When I make a long bridge, or distance myself a bit- I cannot see the end of the bridge/the bridge fully disappears - 64 rope bridge blocks is the maximum length I can see on one axis, at a time... Is there any way to increase the rendering distance of the rope bridge in 1.7.10, Forge 10.13.4.1614 (like to the length of 400)?
Thank you for your time!

![2017-03-04_10 02 44](https://cloud.githubusercontent.com/assets/4314990/23577864/f2f5c38a-00c1-11e7-8b81-a2e2f2da6779.png)
![2017-03-04_10 03 21](https://cloud.githubusercontent.com/assets/4314990/23577865/f2f5fe04-00c1-11e7-8ff7-f4b4e33f1a5a.png)
![2017-03-04_10 03 53](https://cloud.githubusercontent.com/assets/4314990/23577866/f2f9212e-00c1-11e7-8460-1aa670c3b5ad.png)

**Comment by Cazsius** [comment]
1.7.10 is an unsupported version, I apologize.

**Comment by LeoMantys** [comment]
That's ok... it's not a serious issue anyway. Keep up the good work!
