### ISSUE TITLE
Not constructable

### ISSUE THREAD

**Issue by chuckles277** [MrTrollNugNug/Rope-Bridge#42]
Im not able to make either the handle or the barrel, i have all the components and am putting them in the right configuration but neither will build, the hook itself was able to be made. If i could please get some assistance thatd be great as this mod looks great. Im on 1.16 
Thanks -Chuckles

**Comment by KiriCattus** [comment]
I've just checked in build 1.16.5-2.2.0 and things where all craftable there so I'll assume it's an older issue but if it's in an older version or it still occurs do feel free to re-open this issue with more details
