### ISSUE TITLE
Rope bridge not recognising materials. 

### ISSUE THREAD

**Issue by ghost** [MrTrollNugNug/Rope-Bridge#9]
As you can see in the screenshot I clearly have the right amount of materials for the bridge, but I seem's to not be recognising them.

http://i.imgur.com/thk4af8.jpg

(BTW the gun does work in creative, just not survival)

edit: Just a quick update, the ladder gun works correctly, but the ropebridge gun does not.

**Comment by 8BrickDMG** [comment]
I am also experiencing this bug with the current version.

**Comment by Cazsius** [comment]
I've looked into this, and come to the conclusion there is an issue with the # it is displaying. It says you need x slabs and x rope, but that's not the actual number you need, I need to look into the math behind it. Also may have forgot to change it to comply with the config and could be using an old default number per block. Will get back to you guys.

**Comment by 8BrickDMG** [comment]
Ah ok!

I hope you don't mind, I built your last commit which had fixed this issue
for single player and on servers.

**Comment by Cazsius** [comment]
We just released version 2.0.1 with the fixes, just use that now! Was released about an hour ago.

**Comment by 8BrickDMG** [comment]
Awesome! Thanks for that :)
